### ISSUE TITLE
Guide for making a mongo connector

### ISSUE THREAD

**Issue by vijayj** [ankane/blazer-dev#1]
I was looking for a reporting solution and came across blazer which seems perfect. My backend is mongo db (actually parse) and I was thinking of extending blazer to work with mongo. I was wondering if you could give me some guidance on how to get a started. You might have already thought of this - a  wiki on how to write other adapters or plugins for different backend data stores ? Thoughts ?

**Comment by ankane** [comment]
Hey @vijayj, sorry the delayed response. The Blazer readme now has a short section on this: https://github.com/ankane/blazer#creating-an-adapter

Also, MongoDB now has a supported adapter, fwiw.
